---
- name: Stop dovecot
  ansible.builtin.systemd:
    name: dovecot
    state: stopped

- name: Ensure group vmail exists
  ansible.builtin.group:
    name: vmail
    state: present
    gid: 50000

- name: Ensure user vmail exists
  ansible.builtin.user:
    name: vmail
    shell: /sbin/nologin
    groups: vmail
    state: present
    expires: -1
    home: /var/mail

- name: Install dovecot.conf
  ansible.builtin.template:
    src: dovecot.conf.j2
    dest: /etc/dovecot/dovecot.conf
    owner: vmail
    group: dovecot
    mode: '0640'

- name: Replace mail_location in 10-mail.conf
  ansible.builtin.lineinfile:
    path: /etc/dovecot/conf.d/10-mail.conf
    regexp: '^mail_location.*'
    line: 'mail_location = maildir:/var/mail/vhosts/%d/%n/'

- name: Create vhosts directory
  ansible.builtin.file:
    path: "/var/mail/vhosts/{{ server_fqdn }}"
    state: directory
    owner: vmail
    group: vmail
    recurse: true

- name: Disable plaintext_auth
  ansible.builtin.lineinfile:
    path: /etc/dovecot/conf.d/10-auth.conf
    regexp: '^#disable_plaintext_auth.*'
    line: 'disable_plaintext_auth = yes'

- name: Change auth mechanisms
  ansible.builtin.lineinfile:
    path: /etc/dovecot/conf.d/10-auth.conf
    regexp: '^auth_mechanisms = plain'
    line: 'auth_mechanisms = plain login'

- name: Enable authorization sql external 
  ansible.builtin.lineinfile:
    path: /etc/dovecot/conf.d/10-auth.conf
    regexp: '^#!include auth-sql.conf.ext'
    line: '!include auth-sql.conf.ext'

- name: Install auth-sql.conf.ext
  ansible.builtin.template:
    src: auth-sql.conf.ext.j2
    dest: /etc/dovecot/conf.d/auth-sql.conf.ext
    owner: vmail
    group: dovecot
    mode: '0640'

- name: Install dovecot-sql.conf.ext
  ansible.builtin.template:
    src: dovecot-sql.conf.ext.j2
    dest: /etc/dovecot/dovecot-sql.conf.ext
    owner: vmail
    group: dovecot
    mode: '0640'

- name: Tighten dovecot dir permissions
  ansible.builtin.file:
    path: /etc/dovecot
    state: directory
    recurse: true
    mode: '0750'
    owner: vmail
    group: dovecot

- name: Install 10-master.conf
  ansible.builtin.template:
    src: 10-master.conf.j2
    dest: /etc/dovecot/conf.d/10-master.conf
    owner: vmail
    group: dovecot
    mode: '0640'

- name: Require SSL/TLS support
  ansible.builtin.lineinfile:
    path: /etc/dovecot/conf.d/10-ssl.conf
    regexp: '^ssl = yes'
    line: 'ssl = required'

- name: Change SSL cert
  ansible.builtin.lineinfile:
    path: /etc/dovecot/conf.d/10-ssl.conf
    regexp: '^ssl_cert =.*'
    line: 'ssl_cert = <{{ letsencrypt_path }}/fullchain.pem'

- name: Change SSL key
  ansible.builtin.lineinfile:
    path: /etc/dovecot/conf.d/10-ssl.conf
    regexp: '^ssl_key =.*'
    line: 'ssl_key = <{{ letsencrypt_path }}/privkey.pem'

- name: Restart dovecot
  ansible.builtin.systemd:
    name: dovecot
    state: restarted
