services:
  - apache2
  - postfix
  - dovecot
  - opendkim
  - opendmarc

packages:
  - mailutils
  - certbot
  - apache2
  - python3-pymysql
  - python3-certbot-apache
  - postfix 
  - postfix-policyd-spf-python
  - postfix-mysql 
  - postfix-pcre
  - dovecot-core 
  - dovecot-imapd 
  - dovecot-pop3d 
  - dovecot-lmtpd 
  - dovecot-mysql 
  - opendkim 
  - opendkim-tools
  - opendmarc
