---
# Disabled because fetch module does not seem to work properly.
# - hosts: old
#   remote_user: jim
#   become: yes
#   vars_files:
#   - ../vars/main.yml
#   roles:
#   - { role: general, create_backup: true }

- hosts: new
  remote_user: root
  vars_files:
  - defaults/main.yml
  - vars/main.yml
  roles: 
    - role: general
    - role: geerlingguy.mysql
    - role: mysql
    - role: postfix
    - role: dovecot
    - role: zerotier
    - role: opendkim
    - role: opendmarc
    - { role: firewalld, vpn_tunnel_enabled: True }
