---
- name: Check if certificate exists (WWW)
  ansible.builtin.stat:
    path: "/etc/letsencrypt/live/{{ server_www_fqdn }}/cert.pem"
  register: le_cert

- name: Set letsencrypt path (WWW)
  ansible.builtin.set_fact:
    letsencrypt_path: "/etc/letsencrypt/live/{{ server_www_fqdn }}"
  when: le_cert.stat.exists

- name: Check if certificate exists (FQDN)
  ansible.builtin.stat:
    path: "/etc/letsencrypt/live/{{ server_fqdn }}/cert.pem"
  register: le_cert_2

- name: Set letsencrypt path (FQDN)
  ansible.builtin.set_fact:
    letsencrypt_path: "/etc/letsencrypt/live/{{ server_fqdn }}"
  when: le_cert_2.stat.exists
