---
- name: Compress mailbox directory 
  community.general.archive:
    path: "/var/mail/vhosts/{{ server_fqdn }}"
    dest: "/root/{{ mailbox_filename }}"

- name: Store mailbox tarball locally
  ansible.builtin.fetch:
    src: "/root/{{ mailbox_filename }}"
    dest: "./{{ mailbox_filename }}"

- name: remove mailbox tarball from server
  ansible.builtin.file:
    path: "/root/{{ mailbox_filename }}"
    state: absent