---
- name: Download zerotier install script
  ansible.builtin.get_url:
    url: https://install.zerotier.com
    dest: /tmp/zerotier_install_script
    mode: '0755'

- name: Execute installation script
  ansible.builtin.command: /bin/bash /tmp/zerotier_install_script > /root/.zerotier_installed
  args:
    creates: /root/.zerotier_installed

- name: Enable zerotier one service
  ansible.builtin.systemd:
    name: zerotier-one
    state: started
    enabled: yes

- name: Join zerotier network
  ansible.builtin.command: zerotier-cli join "{{ zerotier_network_id }}" > /root/.zerotier_network_joined
  args:
    creates: /root/.zerotier_network_joined

- name: Get server's zerotier address
  ansible.builtin.command: zerotier-cli status
  register: zerotier_address

- name: Print server's zerotier address
  ansible.builtin.debug: 
    msg: "Status: {{ zerotier_address.stdout }}"
