---
- name: Create virtual aliases
  community.mysql.mysql_query:
    login_db: "{{ mysql_database }}"
    single_transaction: true
    query:
      - USE mailserver;
      - INSERT INTO virtual_aliases (domain_id, source, destination) SELECT '{{ item.domain_id }}', '{{ item.source }}@{{ server_fqdn }}', '{{ item.dest }}@{{ server_fqdn }}' WHERE NOT EXISTS (SELECT source FROM mailserver.virtual_aliases WHERE source = '{{ item.source }}@{{ server_fqdn }}');
